apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: github-tests-go-erruoizi
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/github-tests-go-erruoizi:f86c6ffe8b81a541f018b943025c1217b7b75639
          name: container-image
